In [30]:
#import jovian
import math
import numpy as np
import time

In [35]:
A = np.arange(1)
B = np.arange(10000000)

%timeit print(sum(B))

%timeit np.sum(B)

<magic-timeit>:1: RuntimeWarning: overflow encountered in long_scalars


-2014260032
-2014260032
-2014260032
-2014260032
-2014260032
-2014260032
-2014260032
-2014260032
1 s ± 34.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.28 ms ± 166 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
today = np.datetime64("today","D") - np.timedelta64(1,"D")
print(today)

2023-06-10


In [12]:
def checkerboard(shape):
    return np.indices(shape).sum(axis=0) % 2

In [15]:
shapes = (5,6)
print(checkerboard(shapes))

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


In [17]:
import numpy as np
import warnings

# Ignore all NumPy warnings
warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
warnings.filterwarnings("ignore", category=np.RankWarning)
warnings.filterwarnings("ignore", category=np.FloatingPointError)

# Your code goes here...

AttributeError: module 'numpy' has no attribute 'FloatingPointError'

In [16]:
import numpy as np

# Create a 5x5 random matrix
matrix = np.random.rand(5, 5)

# Normalize the matrix using NumPy's normalize function
norm_matrix = (matrix - np.mean(matrix)) / np.std(matrix)

# Print the original and normalized matrices
print("Original matrix:")
print(matrix)
print("\nNormalized matrix:")
print(norm_matrix)

Original matrix:
[[0.1205615  0.8373977  0.70519011 0.96975242 0.40181896]
 [0.76983354 0.93911476 0.6583122  0.11260732 0.83874142]
 [0.57959365 0.80336981 0.01507962 0.68720369 0.32925253]
 [0.61302501 0.44816094 0.14111736 0.56263345 0.38517112]
 [0.04732023 0.29637575 0.7219747  0.95235571 0.68581223]]

Normalized matrix:
[[-1.45390325  1.00234722  0.54933583  1.45586275 -0.49017017]
 [ 0.77083758  1.35088234  0.38870797 -1.48115838  1.00695151]
 [ 0.11897759  0.88575013 -1.81533859  0.48770509 -0.73882017]
 [ 0.23353068 -0.33137863 -1.38346829  0.06086321 -0.54721425]
 [-1.70486562 -0.85147298  0.60684851  1.39625267  0.48293726]]


In [11]:
checkerboard = np.arange(1,65).reshape(8,8)
print(checkerboard)
print()
print(checkerboard[1::2,::2]) 

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]

[[ 9 11 13 15]
 [25 27 29 31]
 [41 43 45 47]
 [57 59 61 63]]


In [108]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [8]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
bag_of_rice = 1.25
profit = 0.20
bags_sold = 500

max_profit = bag_of_rice * profit * bags_sold

print(max_profit)

125.0


In [52]:
result = 1
for i in range(1,7):
    result = result * i
print(result)

720


In [48]:
items = []
for i in range(1,51):
    items.append(i)

In [51]:
print(sorted(items,reverse = True))

[50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [29]:
skills = ["java","python","flutter","reactjs","javascript","nodejs"]

In [31]:
frameworks = ["springboot","material-ui","nextjs","expressjs"]

In [34]:
skills.extend(frameworks)

In [36]:
skills.pop(6)

['springboot', 'material-ui', 'nextjs', 'expressjs']

In [42]:
sorted(skills,reverse=True)

['springboot',
 'reactjs',
 'python',
 'nodejs',
 'nextjs',
 'material-ui',
 'javascript',
 'java',
 'flutter',
 'expressjs']

In [44]:
skills

['expressjs',
 'flutter',
 'java',
 'javascript',
 'material-ui',
 'nextjs',
 'nodejs',
 'python',
 'reactjs',
 'springboot']

In [69]:
def calculate_loan(hse_price,initial_amount, interest_rate,number_of_years, compounds_per_year):
    hse_price = hse_price - initial_amount
    ### P(1 + r/n)^(nt)
    number_of_years = number_of_years *  compounds_per_year 
    result = hse_price * math.pow(1 + (interest_rate / 12),number_of_years)
    return result
    

In [73]:
result = calculate_loan(1260000,300000,0.1,8,12)
print(result)

2129448.6057964335


In [74]:
result = calculate_loan(1260000,0,0.08,10,12)
print(result)

2796746.695526336


In [90]:
age = 19.45678

In [91]:
 if 18 <= age < 60:
    print(age)

19.45678


In [97]:
print("{:.2f}".format(age))
print("{:.2f}".format(age))
print(f"{age:.2f}")

19.46
19.46
19.46


In [104]:
a = 20
b = 30
result = "A is greater" if a>b else "EQUAL" if a==b else "B is greater"
result = "EQUAL" if a==b else "A is greater" if a>b else "B is greater"
result
if a==b "EQUAL" if a>b else "A is greater" else "B is greater" 

SyntaxError: invalid syntax (1996288269.py, line 6)

In [85]:
"michigan" < "oxford" < "stanford"

True

In [89]:
True * False

0

In [87]:
True * True

1

In [88]:
True - True

0

In [105]:
True or False and False


True

In [106]:
False and False

False