In [3]:
import numpy as np

In [1]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x26affa7ab60>)

In [4]:
climate_data = np.genfromtxt(fname="climate.txt",delimiter=",",skip_header=1)

In [6]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

In [7]:
climate_data.shape

(10000, 3)

In [8]:
weights = np.array([0.3,0.2,0.5])

In [11]:
result = climate_data @ weights
result.shape

(10000,)

In [13]:
yieldies = result.reshape(10000,1)

In [14]:
climate_results = np.concatenate((climate_data,yieldies),axis = 1)

In [22]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [19]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [20]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [34]:
np.savetxt("climate_results.txt",climate_results,fmt="%.2f",header="temperature,rainfall,humidity,yield_apples",comments="")

In [19]:
arr = np.array(
   [ [23,24,25,26,27],
    [28,29,30,31,32],
    [13,14,15,16,17],
    [18,19,20,21,22]
   ]
)

In [27]:
arr.shape

(4, 5)

In [28]:
arrs = np.array(
   [ [33,34,35,36,37],
    [38,39,40,41,42],
    [23,24,25,26,27],
    [28,29,30,31,32]
   ]
)

In [29]:
arrs + arr

array([[56, 58, 60, 62, 64],
       [66, 68, 70, 72, 74],
       [36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54]])

In [30]:
arrs * arr

array([[ 759,  816,  875,  936,  999],
       [1064, 1131, 1200, 1271, 1344],
       [ 299,  336,  375,  416,  459],
       [ 504,  551,  600,  651,  704]])

In [40]:
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)
print(np.dot(arr1_np, arr2_np))

-1942957984


In [39]:
print(arr1)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [35]:
arr >= arrs

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [35]:
arr

array([[23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22]])

In [37]:
arr[:,1]

array([24, 29, 14, 19])

In [1]:
# Create a 5x5 matrix with zeros
arr = np.zeros((5, 5))

# Set the values below the diagonal to 1, 2, 3, 4 using fill_diagonal
np.fill_diagonal(arr[1:], [1, 2, 3, 4])

# Print the resulting array
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
